### ISSUE TITLE
按照这个落地DB事务切面应该配置在哪层呢

### ISSUE THREAD

**Issue by fool-persen** [Sayi/ddd-cargo#5]

**Comment by fool-persen** [comment]
比如demo中的用例；save之后需要发送event，如果要保证多个数据提交后进行事件发送，事务切面应该配置在哪层？
application：会导致publish在事务中；
respositoy：需要保证一个respositoyService能够处理全部数据一次录入。
这个场景是如何落地解决的。

**Comment by SilencePuppy** [comment]
我也有同样的问题，请问您那边现在是如何解决的

**Comment by Sayi** [comment]
https://mp.weixin.qq.com/s/R-jBnPhWJHs7J-4CETV88A  扫码微信公众号看下留言。 @SilencePuppy
